### ISSUE TITLE
Inaktivität

### ISSUE THREAD

**Issue by akless** [m0xai/hbrs-we#1]
Es gibt noch immer keinen ersten Commmit. Bitte unbedingt dran denken, regelmäßig an der Homepage zu arbeiten. Die regelmäßigen Commits dienen später als Nachweis, dass es sich bei der Hausarbeit um ihre eigene individuelle Prüfungsleistung handelt. Dies ist Ihre 1. Verwarnung.

**Comment by m0xai** [comment]
Ich habe meine erste Loesung von Aufgabenblatt 1 in die Project hinzugefuegt
