### ISSUE TITLE
Bewertung der Hausarbeit

### ISSUE THREAD

**Issue by akless** [m0xai/hbrs-we#2]
HTML (3/5)
- [x] U1 A7: HTML-Wireframe (3/5)

CSS (4/5)
- [x] U2 A4: Wireframe mit HTML und CSS (4/5)

Responsive Web Design (19/20)
- [x] Homepage: Media Queries (5/5)
- [x] Homepage: Flexbox (5/5)
- [x] Homepage: Grid (5/5)
- [x] Homepage: RWD-Gesamteindruck (4/5)

JavaScript: DOM (10/15)
- [x] U5 A2: Rednerliste (3/5)
- [x] Homepage: DOM-Selektion (2/5)
- [x] Homepage: DOM-Manipulation (5/5)

JavaScript: ES6 (10/10)
- [x] Homepage: Module (5/5)
- [x] Homepage: Template Strings (5/5)

JavaScript: Funktionale Programmierung (11/15)
- [x] U7 A2: Textanalyse mit filter-map-reduce (1/5)
- [x] Homepage: Arrow Functions (5/5)
- [x] Homepage: Kurzer Erklärartikel zu „Spread“-Operator mit Beispiel (5/5)

JavaScript: Asynchrones JS (15/15)
- [x] U8 A1: Promises (5/5)
- [x] U8 A2: async/await (5/5)
- [x] Homepage: fetch-API (5/5)

SVG (9/10)
- [x] U9 A3: Interaktive SVG Grafik (4/5)
- [x] Homepage: Kurze Demonstration von translate, rotate und scale (5/5)

Homepage (6/10)
- [x] Solution-Navigator (3/5)
- [x] Gesamteindruck (3/5)

Video (12/15)
- [x] Inhalt (8/10)
- [x] Präsentation (4/5)

Gesamt: 102/120P
Note: 1,7

**Comment by m0xai** [comment]
Vielen Dank!
